M48
; DRILL file {KiCad 9.0.1+1} date 2025-09-06T16:26:38+0000
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2025-09-06T16:26:38+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X-32496Y46425
T2
X-32496Y25425
M30
